### ISSUE TITLE
无法上传，提示8005

### ISSUE THREAD

**Issue by erbukuawu** [dream10201/115Docker#1]
![image](https://github.com/user-attachments/assets/b59399e4-d0d8-4f86-a1f0-e649183e6909)
如图所示，上传文件会提示“上传异常[8005]，请重试”是什么原因啊大佬
安装的版本是最新的
![image](https://github.com/user-attachments/assets/877824a3-4625-4e95-834d-03f0cb60b0c1)

**Comment by dream10201** [comment]
普通带桌面环境的linux用115浏览器能上传吗？

**Comment by dream10201** [comment]
我用虚拟机安装了带桌面的debian，同样的错误

**Comment by erbukuawu** [comment]
> 我用虚拟机安装了带桌面的debian，同样的错误

哦哦好的，那就是说这个是官方的问题，只能等官方修复了是吧

**Comment by dream10201** [comment]
> > 我用虚拟机安装了带桌面的debian，同样的错误
> 
> 哦哦好的，那就是说这个是官方的问题，只能等官方修复了是吧

我测试是这样的，你有条件的话也试试

**Comment by dream10201** [comment]
再次验证，官方的没问题，但是研究了一下午没找到问题所在

**Comment by erbukuawu** [comment]
> 再次验证，官方的没问题，但是研究了一下午没找到问题所在

目前情况是支持秒传的文件是可以正常上传的，不支持秒传的就会提示8005，而且我还发现一个bug,就是在剪切板里面输入中文后在浏览器里面粘贴会变成乱码
![17156](https://github.com/user-attachments/assets/54888088-6cbe-4fc4-85e2-ab66406c6799)

**Comment by Xiong-China** [comment]
8005 是因为你登录的设备太多 试试单设备吧 不行就等修复 
现在用刮削都有问题 官方都限制了

**Comment by dream10201** [comment]
> 8005 是因为你登录的设备太多 试试单设备吧 不行就等修复 现在用刮削都有问题 官方都限制了

应该不是，具体原因不知道，但是我找到解决办法了

**Comment by dream10201** [comment]
@erbukuawu  最新版本已经修复，现在可以上传了

**Comment by erbukuawu** [comment]
> @erbukuawu 最新版本已经修复，现在可以上传了

果然可以了，大佬666，非常感谢👍️，现在可以愉快地玩耍了
