### ISSUE TITLE
为什么下载提示磁盘空间不足

### ISSUE THREAD

**Issue by lw6644700** [dream10201/115Docker#10]
下载了原盘几十G的提示磁盘空间不足，好像有两个1g和4G左右的视频就可以下载，这是为什么？我硬盘还有1T多

**Comment by dream10201** [comment]
> 下载了原盘几十G的提示磁盘空间不足，好像有两个1g和4G左右的视频就可以下载，这是为什么？我硬盘还有1T多

确认下挂载目录，最新版有更新挂载目录

**Comment by lw6644700** [comment]
挂在目录没错，映射的容器内路径是/opt/Downloads，下载文件夹也在我本地出现了，但是因为提示磁盘空间不足，所以下载不成功

**Comment by dream10201** [comment]
> 挂在目录没错，映射的容器内路径是/opt/Downloads，下载文件夹也在我本地出现了，但是因为提示磁盘空间不足，所以下载不成功

贴一下你的docker命令以及df -h的输出

**Comment by lw6644700** [comment]
我是unraid安装的

![image](https://github.com/user-attachments/assets/6d176aa4-62ae-4199-b33f-165f8352e11f)
![image](https://github.com/user-attachments/assets/5c40feb8-2046-432e-9c18-e990aedbf49f)

**Comment by dream10201** [comment]
没看出来什么问题，你试试在主机上复制一个几十G的文件到那块硬盘，看能否成功

**Comment by lw6644700** [comment]
> 没看出来什么问题，你试试在主机上复制一个几十G的文件到那块硬盘，看能否成功

复制进去没问题的，包括我docker的QB和TR下载pt原盘什么的都不会空间不足，就是您的115浏览器会提示不能下载，具体没试，丢了一堆任务进去，好像只有4-5G内的能下载，其它都报磁盘空间不足

**Comment by dream10201** [comment]
我试了下没啥问题啊
<img width="1255" alt="image" src="https://github.com/user-attachments/assets/c670e947-bc9a-4546-af79-0e618acb2743">

**Comment by lw6644700** [comment]
> 我试了下没啥问题啊 <img alt="image" width="1255" src="https://private-user-images.githubusercontent.com/20334372/391230099-c670e947-bc9a-4546-af79-0e618acb2743.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NzMxODQsIm5iZiI6MTczMjk3Mjg4NCwicGF0aCI6Ii8yMDMzNDM3Mi8zOTEyMzAwOTktYzY3MGU5NDctYmM5YS00NTQ2LWFmNzktMGU2MThhY2IyNzQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDEzMjEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MWNjYzM4NWJmYTk3MTVlZjMzOGVmMjJkZDcwYWE5OTdjNDY5ZGQ1OGU3MmM3MTMzOTAwNjRjYjdlYjRjMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ywQv7JjHE1mQlI33s7H6kPkf2jBOCZsZ6s5RrGmsV68">

搞不懂😄，磁盘映射也和其它docker程序一样，难道115浏览器和unraid之间有点什么需要设置的才能下载？

**Comment by lw6644700** [comment]
上传文件都是能正常读取，多大都行

**Comment by dream10201** [comment]
有人提过unraid权限的问题，你看看你用的什么用户，设置一下
--user 0:0
userid和groupid

**Comment by lw6644700** [comment]
> 有人提过unraid权限的问题，你看看你用的什么用户，设置一下 --user 0:0 userid和groupid

我直接用root账户的，docker直接开了特权，关键不是所有文件下不了，是大文件下不了，如果权限问题应该都下不了吧？我试试添加root进去

**Comment by lw6644700** [comment]
> userid和groupid

添加了不行😓

**Comment by dream10201** [comment]
@lw6644700 没用过unraid，没法提供更多帮助，找chargpt问了下，有几个点，你看看
### 原因：Unraid 的共享文件夹可能设置了“最小可用空间”限制，导致文件无法写入。
解决方法：
    登录 Unraid 的 Web 管理界面。
    进入 Shares 页面，找到对应的共享文件夹。
    检查并调整 Minimum free space（最小可用空间）的值。
        建议设置为稍大于你要下载的文件大小，以避免写入失败。
### 原因：如果 Unraid 配置了缓存盘，Docker 可能先写入缓存盘，再由后台转移到硬盘。如果缓存盘满了，就会提示空间不足。
解决方法：
    检查缓存盘的可用空间：
df -h /mnt/cache
如果缓存盘已满：
    调整文件转移策略：进入 Settings -> Scheduler，设置定期将缓存文件转移到硬盘。
    或直接关闭缓存功能，将数据直接写入硬盘（会稍微降低写入速度）。

### 原因：Docker 容器的存储层可能设置了大小限制，超出后即使宿主机有空间，仍然会报错。
解决方法：
    检查 Docker 容器的磁盘空间：
docker inspect mycontainer | grep -i size
如果存在限制，可以调整 Docker Daemon 的存储配置：
    修改 Docker 的 daemon.json 文件，取消或增大默认存储大小：
```
{
    "storage-driver": "overlay2",
    "storage-opts": [
        "overlay2.size=50G"
    ]
}
```
重启 Docker 服务后重新运行容器。

### 原因：Unraid 会根据分配策略（Allocation Method）将文件写入特定的硬盘。如果某个硬盘已满，即使其他硬盘有空间，也会提示错误。
解决方法：
    在 Unraid 的共享设置中，检查分配策略：
        High-Water：先填满一半空间，然后再分配到其他磁盘。
        Most-Free：优先写入剩余空间最多的磁盘。
        Fill-Up：优先填满当前磁盘，再写入下一个。
    修改分配策略为 Most-Free，以便更灵活地使用空间。
