### ISSUE TITLE
无法安装扩展，提示程序包无效

### ISSUE THREAD

**Issue by erbukuawu** [dream10201/115Docker#11]
如图所示
![image](https://github.com/user-attachments/assets/944dd691-04ee-4523-8fd7-8a766f68d299)
版本[latest](https://hub.docker.com/layers/xiuxiu10201/115/latest/images/sha256-a19121dd8772ae00949926b0bc29cb03f2a798274c03584df96f745afc5181b3?context=explore)

**Comment by dream10201** [comment]
检查下网络

**Comment by erbukuawu** [comment]
> 检查下网络

应该不是网络的问题，因为我就是在chrome官方应用商店下载的，而且换了好几个节点依然不行

**Comment by boreascn** [comment]
同样有这个问题，不知道是115浏览器自己的问题还是这个docker的问题。不过篡改猴可以用115自带的应用商店的，那个可以装。但是ublock没有找到替代

**Comment by erbukuawu** [comment]
> 同样有这个问题，不知道是115浏览器自己的问题还是这个docker的问题。不过篡改猴可以用115自带的应用商店的，那个可以装。但是ublock没有找到替代

应该是bug，之前我是可以正常安装的，更新后所有插件都没了，重新安装就是提示程序包无效了

**Comment by dream10201** [comment]
> > 同样有这个问题，不知道是115浏览器自己的问题还是这个docker的问题。不过篡改猴可以用115自带的应用商店的，那个可以装。但是ublock没有找到替代
> 
> 应该是bug，之前我是可以正常安装的，更新后所有插件都没了，重新安装就是提示程序包无效了

更新是指115的更新还是这个项目的更新？

**Comment by erbukuawu** [comment]
> > > 同样有这个问题，不知道是115浏览器自己的问题还是这个docker的问题。不过篡改猴可以用115自带的应用商店的，那个可以装。但是ublock没有找到替代
> > 
> > 
> > 应该是bug，之前我是可以正常安装的，更新后所有插件都没了，重新安装就是提示程序包无效了
> 
> 更新是指115的更新还是这个项目的更新？

我在电脑 上装了个Windows版的115浏览器，版本27.0.7.5，发现也是同样情况，提示程序包无效，看来是115官方的问题了
![image](https://github.com/user-attachments/assets/bbf6e0f0-2e8e-4250-a585-56be92f3b993)
