### ISSUE TITLE
内置浏览器显示无法访问此网站

### ISSUE THREAD

**Issue by jg070475** [dream10201/115Docker#12]
![QQ20241202-214433](https://github.com/user-attachments/assets/ac3f58dc-61f3-4daa-9b61-ed9647a3b14a)

大佬，docker建好后内置浏览器显示无法访问此网站。我的机器是群晖，用群晖的工具建的docker。

**Comment by dream10201** [comment]
是不是docker没给网络权限

**Comment by jg070475** [comment]
已解决，感谢

**Comment by dream10201** [comment]
> > 是不是docker没给网络权限
> 
> 搞定能用了。但是有个问题，不能复制下载链接到docker内。需要在外面添加下载链接完成再到docker下载，有点繁琐。希望添加一个可以在外部复制链接内容进入容器内部的功能。

左边又个复制粘贴的，这个没办法解决，VNC的老问题了
