### ISSUE TITLE
部署在极空间后，无限重启，请教下大佬是遇到了什么问题

### ISSUE THREAD

**Issue by Clazzi76** [dream10201/115Docker#13]
无论是使用极空间自带的Docker管理，还是使用Portainer部署，都会遇到一直在重启的问题，本人完全小白，请大佬指点一下，谢谢！

使用的部署yaml如下：
version: "3"

services:
  "115":
    image: xiuxiu10201/115:latest
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      PASSWORD: "123456"
      DISPLAY_WIDTH: "1920"
      DISPLAY_HEIGHT: "1080"
    volumes:
      - /tmp/zfsv3/nvme11/手机号打码/data/115Docker:/etc/115    # 115浏览器数据目录
      - /tmp/zfsv3/sata1/手机号打码/data/115Download:/opt/Downloads    # 下载目录
    ports:
      - "1150:1150"     # 端口映射
      - "1152:1152"     # 端口映射

[2024_12_14 10_20_00_log.txt](https://github.com/user-attachments/files/18133933/2024_12_14.10_20_00_log.txt)
Docker的日志如下：
�2024-12-14T02:15:25.675897719Z ~/.vnc is deprecated, please consult 'man vncsession' for paths to migrate to. at /usr/libexec/vncserver line 43.
@2024-12-14T02:15:25.700142594Z Warning: could not find self.pem
r2024-12-14T02:15:25.700942773Z Using local websockify at /usr/share/usr/local/share/noVNCdim/utils/websockify/run
=2024-12-14T02:15:25.723884218Z Using desktop session openbox
T2024-12-14T02:15:25.729625266Z Starting webserver and WebSockets proxy on port 1150
 2024-12-14T02:15:25.844281640Z 
U2024-12-14T02:15:25.844423358Z New '89bacdf4198e:115 ()' desktop is 89bacdf4198e:115
 2024-12-14T02:15:25.844477325Z 
@2024-12-14T02:15:25.844535194Z Starting desktop session openbox
 2024-12-14T02:15:25.926193861Z 
 2024-12-14T02:15:26.279881008Z 
Q2024-12-14T02:15:26.280003667Z Xvnc TigerVNC 1.14.1 - built Oct 24 2024 09:35:40
f2024-12-14T02:15:26.280109668Z Copyright (C) 1999-2024 TigerVNC Team and many others (see README.rst)
Y2024-12-14T02:15:26.280249071Z See https://www.tigervnc.org for information on TigerVNC.
D2024-12-14T02:15:26.280369894Z Underlying X server release 12101013
 2024-12-14T02:15:26.280424552Z 
?2024-12-14T02:15:26.280710878Z Could not find any render nodes
C2024-12-14T02:15:26.280812916Z Failed to initialize DRI3 extension
 2024-12-14T02:15:26.457600811Z 
82024-12-14T02:15:26.457696877Z Sat Dec 14 10:15:26 2024
D2024-12-14T02:15:26.457772874Z  vncext:      VNC extension running!
j2024-12-14T02:15:26.458185755Z  vncext:      Listening for VNC connections on all interface(s), port 6015
M2024-12-14T02:15:26.458291614Z  vncext:      created VNC server for screen 0
o2024-12-14T02:15:26.766743996Z [mi] mieq: warning: overriding existing handler (nil) with 0x636170 for event 2
o2024-12-14T02:15:26.766909136Z [mi] mieq: warning: overriding existing handler (nil) with 0x636170 for event 3
`2024-12-14T02:15:26.768956468Z xinit: XFree86_VT property unexpectedly has 0 items instead of 1
 2024-12-14T02:15:27.181121647Z 
 2024-12-14T02:15:27.181300489Z 
52024-12-14T02:15:27.181365190Z Navigate to this URL:
 2024-12-14T02:15:27.181422300Z 
a2024-12-14T02:15:27.182678473Z     http://89bacdf4198e:1150/vnc.html?host=89bacdf4198e&port=1150
 2024-12-14T02:15:27.182818706Z 
42024-12-14T02:15:27.182869439Z Press Ctrl-C to exit
 2024-12-14T02:15:27.182910863Z 
 2024-12-14T02:15:27.182949541Z 
�2024-12-14T02:15:29.160448564Z tint2: Using glib slice allocator (default). Run tint2 with environment variable G_SLICE=always-malloc in case of strange behavior or crashes
>2024-12-14T02:15:29.201814414Z tint2: xRandr: Found crtc's: 1
x2024-12-14T02:15:29.206613525Z [1;34mtint2: xRandr: Linking output VNC-0 with crtc 0, resolution 1920x1080, DPI 96[0m
�2024-12-14T02:15:29.536827813Z ** Message: 10:15:29.536: x-terminal-emulator has very limited support, consider choosing another terminal
 2024-12-14T02:15:29.580642053Z 
�2024-12-14T02:15:29.580901888Z ** (pcmanfm:45): WARNING **: 10:15:29.580: The directory '~/Templates' doesn't exist, ignoring it
 2024-12-14T02:15:29.717448843Z 
�2024-12-14T02:15:29.717593005Z (pcmanfm:45): GLib-ERROR **: 10:15:29.717: file ../../../glib/gthread-posix.c: line 1340 (g_system_thread_new): error '不允许的操作' during 'pthread_create'
B2024-12-14T02:15:29.794399856Z xinit: connection to X server lost
!2024-12-14T02:15:29.794545655Z 
B2024-12-14T02:15:29.794589267Z waiting for X server to shut down 
82024-12-14T02:15:29.794634499Z Sat Dec 14 10:15:29 2024
S2024-12-14T02:15:29.794671854Z  ComparingUpdateTracker: 0 pixels in / 0 pixels out
G2024-12-14T02:15:29.794739395Z  ComparingUpdateTracker: (1:-nan ratio)
i2024-12-14T02:15:30.315397614Z /opt/run.sh: 第 20 行：   45 追踪与中断点陷阱pcmanfm --desktop
@2024-12-14T02:15:49.832338884Z Warning: could not find self.pem
r2024-12-14T02:15:49.833084554Z Using local websockify at /usr/share/usr/local/share/noVNCdim/utils/websockify/run
�2024-12-14T02:15:49.834418191Z ~/.vnc is deprecated, please consult 'man vncsession' for paths to migrate to. at /usr/libexec/vncserver line 43.
T2024-12-14T02:15:49.866523206Z Starting webserver and WebSockets proxy on port 1150
=2024-12-14T02:15:49.894629780Z Using desktop session openbox
 2024-12-14T02:15:50.045867355Z 
U2024-12-14T02:15:50.045985532Z New '89bacdf4198e:115 ()' desktop is 89bacdf4198e:115
 2024-12-14T02:15:50.046037063Z 
@2024-12-14T02:15:50.046081352Z Starting desktop session openbox
 2024-12-14T02:15:50.101351788Z 
 2024-12-14T02:15:50.494012038Z 
Q2024-12-14T02:15:50.494212291Z Xvnc TigerVNC 1.14.1 - built Oct 24 2024 09:35:40
f2024-12-14T02:15:50.494409354Z Copyright (C) 1999-2024 TigerVNC Team and many others (see README.rst)
Y2024-12-14T02:15:50.494488121Z See https://www.tigervnc.org for information on TigerVNC.
D2024-12-14T02:15:50.494553314Z Underlying X server release 12101013
 2024-12-14T02:15:50.494599195Z 
?2024-12-14T02:15:50.494789291Z Could not find any render nodes
C2024-12-14T02:15:50.494897579Z Failed to initialize DRI3 extension
 2024-12-14T02:15:50.658089037Z 
82024-12-14T02:15:50.658240939Z Sat Dec 14 10:15:50 2024
D2024-12-14T02:15:50.658299515Z  vncext:      VNC extension running!
j2024-12-14T02:15:50.658753532Z  vncext:      Listening for VNC connections on all interface(s), port 6015
M2024-12-14T02:15:50.658859670Z  vncext:      created VNC server for screen 0
o2024-12-14T02:15:51.040960718Z [mi] mieq: warning: overriding existing handler (nil) with 0x636170 for event 2
o2024-12-14T02:15:51.041191336Z [mi] mieq: warning: overriding existing handler (nil) with 0x636170 for event 3
`2024-12-14T02:15:51.042582728Z xinit: XFree86_VT property unexpectedly has 0 items instead of 1
 2024-12-14T02:15:51.367855027Z 
 2024-12-14T02:15:51.368372505Z 
52024-12-14T02:15:51.368556933Z Navigate to this URL:
 2024-12-14T02:15:51.368610849Z 
a2024-12-14T02:15:51.370970956Z     http://89bacdf4198e:1150/vnc.html?host=89bacdf4198e&port=1150
 2024-12-14T02:15:51.371085730Z 
42024-12-14T02:15:51.371210299Z Press Ctrl-C to exit
 2024-12-14T02:15:51.371286507Z 
 2024-12-14T02:15:51.371359394Z 
�2024-12-14T02:15:53.175231320Z tint2: Using glib slice allocator (default). Run tint2 with environment variable G_SLICE=always-malloc in case of strange behavior or crashes
>2024-12-14T02:15:53.274604166Z tint2: xRandr: Found crtc's: 1
x2024-12-14T02:15:53.279053658Z [1;34mtint2: xRandr: Linking output VNC-0 with crtc 0, resolution 1920x1080, DPI 96[0m
�2024-12-14T02:15:53.696004500Z ** Message: 10:15:53.695: x-terminal-emulator has very limited support, consider choosing another terminal
 2024-12-14T02:15:53.838325945Z 
�2024-12-14T02:15:53.838488266Z ** (pcmanfm:43): WARNING **: 10:15:53.838: The directory '~/Templates' doesn't exist, ignoring it
 2024-12-14T02:15:53.876085929Z 
�2024-12-14T02:15:53.876190197Z (pcmanfm:43): GLib-ERROR **: 10:15:53.875: file ../../../glib/gthread-posix.c: line 1340 (g_system_thread_new): error '不允许的操作' during 'pthread_create'
B2024-12-14T02:16:00.184892059Z xinit: connection to X server lost
!2024-12-14T02:16:00.186021913Z 
B2024-12-14T02:16:00.186534361Z waiting for X server to shut down 
82024-12-14T02:16:00.186800455Z Sat Dec 14 10:16:00 2024
S2024-12-14T02:16:00.186901807Z  ComparingUpdateTracker: 0 pixels in / 0 pixels out
G2024-12-14T02:16:00.186977411Z  ComparingUpdateTracker: (1:-nan ratio)
i2024-12-14T02:16:00.422224877Z /opt/run.sh: 第 20 行：   43 追踪与中断点陷阱pcmanfm --desktop

**Comment by dream10201** [comment]
看起来是docker版本的问题？能用最新的docker试试吗？

**Comment by Clazzi76** [comment]
> 看起来是docker版本的问题？能用最新的docker试试吗？

谢谢回复，我试一下。

**Comment by Clazzi76** [comment]
更新了Docker引擎后，依然是无限重启，悲
上传了日志，再请教下大佬看看是什么问题
[2024_12_16 15_23_27_log.txt](https://github.com/user-attachments/files/18146264/2024_12_16.15_23_27_log.txt)

Docker的日志截图如下：
<img width="556" alt="未命名 42" src="https://github.com/user-attachments/assets/05a054d9-5949-44ca-bfe5-12b66731899f" />

**Comment by dream10201** [comment]
运行命令加一个环境变量试试
```
G_SLICE=always-malloc
```

**Comment by dream10201** [comment]
我没有对应设备，没法提供更多帮助，但是我找到类似的问题，你可以参照一下：https://github.com/docker-library/golang/issues/467

**Comment by Clazzi76** [comment]
> 我回答没有设备，无法提供更多帮助，但是我找到类似的问题，你可以参照一下： [matrixorigin/matrixorigin.io.cn#508 ](https://github.com/matrixorigin/matrixorigin.io.cn/issues/508) [docker-library/golang#467](https://github.com/docker-library/golang/issues/467)

非常感谢，我自己也去找AI工具尝试解决下。
