### ISSUE TITLE
cookies的问题

### ISSUE THREAD

**Issue by mizhewei** [dream10201/115Docker#15]
只填3个环境变量 似乎会报错无法登录

**Comment by dream10201** [comment]
具体错误是什么

**Comment by 1013510225** [comment]
> 具体错误是什么

https://github.com/1013510225
看我的这个，Cookie缺少 KID ，115前几周更新后添加了KID，如果缺少，登录会显示已退出。

**Comment by 1013510225** [comment]
> 具体错误是什么

https://registry.hub.docker.com/r/1013510225/115linux
你快赶工修复，修好就删了拉取你的镜像。🙃

**Comment by dream10201** [comment]
IOS APP貌似还没有这个KID。已经加上了，你试试
