### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by Wdx1980102488888888** [dream10201/115Docker#16]
IP:1150/vnc.html 登录后，要输入密码。不知道密码是多少。

**Comment by Wdx1980102488888888** [comment]
![Uploading 微信图片_20241217192929.png…]()

**Comment by Wdx1980102488888888** [comment]
![image](https://github.com/user-attachments/assets/31a288af-ecc7-4c41-a093-9c039569264a)

**Comment by dream10201** [comment]
文档的环境变量PASSWORD就是密码
