### ISSUE TITLE
设置用户ID和组ID后不能读取cookie

### ISSUE THREAD

**Issue by dengzhan007** [dream10201/115Docker#19]
unraid下用--user 0:0运行docker会导致下载的文件权限为-rw-------，
如果手动改成SMB用户的ID，启动docker会提示不能读取设置，cookie也不能读取了

**Comment by dream10201** [comment]
1、SMB的用户在是独立的吧？系统里有没有对应用户？
2、改了用户/组之后，之前的配置文件夹以及文件也需要改用户/组。

**Comment by dengzhan007** [comment]
> 1、SMB的用户在是独立的吧？系统里有没有对应用户？ 2、改了用户/组之后，之前的配置文件夹以及文件也需要改用户/组。

改配置文件夹的权限可以读取配置了，但还是因为权限是-rw-------导致只有一个用户能读取，多用户用不了，有什么方法能让下载的文件默认权限就是-rw-rw-rw-吗

**Comment by dream10201** [comment]
没记错的话，这个貌似是115浏览器的行为。暂时没法改

**Comment by dengzhan007** [comment]
> 没记错的话，这个貌似是115浏览器的行为。暂时没法改

感谢大佬
