### ISSUE TITLE
国外机器部署之后无法打开

### ISSUE THREAD

**Issue by 5536086** [dream10201/115Docker#2]
机子是国外的。ip:1150可以正常打开文件列表，但是点开vnc.html文件，无法连接到VNC

**Comment by dream10201** [comment]
重新拉一下镜像试试，上一版镜像有问题

**Comment by 5536086** [comment]
> 重新拉一下镜像试试，上一版镜像有问题

好，我试试

**Comment by dream10201** [comment]
可以检查下端口占用，1150 1152两个端口

**Comment by o2e** [comment]
@dream10201 和机器，端口没关系能进到vnc的系统桌面 双击115图标打不开没反应 没有日志看不到原因

**Comment by o2e** [comment]
@5536086 试试
```compose
environment:
   - XDG_CONFIG_HOME=/tmp/.chromium
   - XDG_CACHE_HOME=/tmp/.chromium
```

**Comment by dream10201** [comment]
我用vps测试没问题，尝试下这个命令
```bash
docker run --name=115 \
-v /tmp:/root/Downloads \
--env PASSWORD=123456 \
--rm --network=host -d --tmpfs /tmp \
--label io.containers.autoupdate=registry \
--env TZ=Asia/Shanghai \
docker.io/xiuxiu10201/115:latest
```

**Comment by o2e** [comment]
> 我用vps测试没问题，尝试下这个命令
> 
> ```shell
> docker run --name=115 \
> -v /tmp:/root/Downloads \
> --env PASSWORD=123456 \
> --rm --network=host -d --tmpfs /tmp \
> --label io.containers.autoupdate=registry \
> --env TZ=Asia/Shanghai \
> docker.io/xiuxiu10201/115:latest
> ```
看下你拉取的浏览器版本是多少 是不是缓存到了老版本所有没有bug？我这边fork代码推送到dockerhub上去再拉取是老版本的代码 有缓存(删除了本地镜像文件也是一样)

**Comment by dream10201** [comment]
> > 我用vps测试没问题，尝试下这个命令
> > ```shell
> > docker run --name=115 \
> > -v /tmp:/root/Downloads \
> > --env PASSWORD=123456 \
> > --rm --network=host -d --tmpfs /tmp \
> > --label io.containers.autoupdate=registry \
> > --env TZ=Asia/Shanghai \
> > docker.io/xiuxiu10201/115:latest
> > ```
> 
> 看下你拉取的浏览器版本是多少 是不是缓存到了老版本所以没问题？我这边fork代码推送到dockerhub上去再拉取是老版本的代码 有缓存(删除了本地镜像文件也是一样) 。下午自己改了一通可以运行了，主要进行了以下操作
> 
> > ```
> > environment:
> >    - XDG_CONFIG_HOME=/tmp/.chromium
> >    - XDG_CACHE_HOME=/tmp/.chromium
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `/opt/115`的目录应该还要给docker运行用户的权限
> 
> 可以把这里log写到tmp之类的地方 方便查错误信息
> 
> https://github.com/dream10201/115Docker/blob/0519130a01877c99f6263f48496af2dfa5ee404b/Dockerfile#L74

缓存应该不是，我调试到现在没出现缓存问题，可能是因为我用的podman，不过你这个更新加上去了，可以试试

**Comment by Xiong-China** [comment]
大陆不能拉取 自己Fork一下 用aliyun构建

**Comment by 5536086** [comment]
解决了，把容器和镜像全部完全删除之后再重新拉取部署就可以了
