### ISSUE TITLE
上传8005错误

### ISSUE THREAD

**Issue by 12black** [dream10201/115Docker#6]
镜像已经更新到最新 还是会出现8005错误
![image](https://github.com/user-attachments/assets/0f174356-7808-4849-8ba4-13c81028f8c0)

**Comment by dream10201** [comment]
检查一下是不是缓存问题：https://github.com/dream10201/115Docker/issues/2#issuecomment-2485125953
然后看看自己是不是登录太多设备了：https://github.com/dream10201/115Docker/issues/1#issuecomment-2486210253
我刚测试了一下，没有问题

**Comment by dream10201** [comment]
如果上面列的都没问题，电脑安装一个试着上传你这几个文件试试，看会不会出同样的问题

**Comment by 12black** [comment]
![image](https://github.com/user-attachments/assets/995a1d4b-383d-4544-af62-ab8b4f2adff1)
他不是所有都失败，有些可以有些不行

**Comment by dream10201** [comment]
你试着自己新建一个文件，文件内容随机填写一些内容，看看能否上传。上一个8005问题是除了能秒传的文件外不能上传。

**Comment by 12black** [comment]
我把容器和镜像都删了重新弄可以了
