### ISSUE TITLE
Unraid下因为权限问题，下载的文件默认无法打开/移动，建议添加权限变量

### ISSUE THREAD

**Issue by tyhunter** [dream10201/115Docker#9]
大佬好，我发现在Unraid下因为Docker创建的文件默认都是-rw-------，无法被普通用户通过SMB访问/移动，参考了其他项目也有这种问题存在的，作者添加了一个权限变量去修改docker运行的权限：https://github.com/cnk3x/xunlei/issues/85
想看下能否添加这块的支持呢，辛苦大佬

`XL_UID: "1000" #运行迅雷的用户ID
XL_GID: "100" #运行迅雷的用户组ID`

**Comment by dream10201** [comment]
@tyhunter 用这个试试看能否解决你的问题：
```shell
docker pull docker.io/xiuxiu10201/115:dev
```

**Comment by dream10201** [comment]
@tyhunter 试试看能否解决你的问题：

将user改为你需要的用户id和组id
然后映射目录有做修改
数据目录：/etc/115
下载目录：/opt/Downloads

```shell
docker run --name=115 \
--user 1001:1001
--env PASSWORD=123456 \
--env DISPLAY_WIDTH=1920 \
--env DISPLAY_HEIGHT=1080 \
--rm --network=host -d --tmpfs /tmp \
--label io.containers.autoupdate=registry \
--env TZ=Asia/Shanghai \
docker.io/xiuxiu10201/115:dev
```

**Comment by tyhunter** [comment]
@dream10201 感谢大佬还特意更新了版本，我这两天出差了等周末尝试一下，辛苦大佬

**Comment by tyhunter** [comment]
@dream10201 感谢大佬，周末试了下可以使用，用SMB登录账户的userid和groupid做映射就可以成功读写下载文件
